### ISSUE TITLE
`next` and `genRange` are (?mistakenly) deprecated. Even though they are now using the efficient implementation from `splitmix` library

### ISSUE THREAD

**Issue by 2jacobtan** [haskell/random#114]
`next` and `genRange` should not be deprecated.

The implementation in random-1.1 was inefficient, relying on `Integer`.

But in random-1.2, this has been fixed (using `splitmix` library's implementation), so the deprecation looks unnecessary.

---

https://github.com/haskell/random/blob/master/src/System/Random/Internal.hs#L108-L122

https://hackage.haskell.org/package/random-1.2.0/docs/System-Random.html#v:next

**Comment by lehins** [comment]
@2jacobtan Underlying PRNG algorithm was only part of the problem, so performance fix was not only due to switch to splitmix. In fact `next` and `genRange` were the real culprit of all performance issues in `random`. It was because of those two functions that every PRNG with `RandomGen` instance had to go through `Integer`. See this blog post for more info: https://alexey.kuleshevi.ch/blog/2019/12/21/random-benchmarks/ 

So, no, deprecation was not a mistake, it was actually a requirement.

Feel free to re-open the ticket and submit a PR with benchmarks if you have any ideas on how to improve performance of `random` with or without `next`/`genRange`

**Comment by 2jacobtan** [comment]
Thanks! It's clear now. I have a suggestion to clarify the comment on `next`:

I took the hint from your reply, then looked at the v1.1 source code for `random`. Now I know that the bad algorithm of v1.1 `random` happened to (mis)use `next`. (This wasn't mentioned in the blog post.)

However without the above context, I got confused reading the v1.2 comment on `next`: "Using next is inefficient as all operations go via Integer."

Because my naive interpretation of the comment was that `next` itself is slow. Which is not true. (`next :: SMGen -> (Int, SMGen)` is `System.Random.SplitMix.nextInt`, which is technically perfectly fast (=efficient), as you tested to be 2ms in the blog post)

So, I think `next` itself is innocent. The fault was with `random` for misusing `next`.

It would be clearer to say that the old v1.1 `random` using `next` was inefficient. And the new v1.2 has a better algorithm, which no longer uses `next`, so `next` is now redundant (and can be deprecated).

**Comment by lehins** [comment]
First of all, `next` was never meant to be used by the end user, it was designed for PRNG implementors. `Random` class was designed to be used for random number generation! So I am a bit at a loss why you even worry about `next` and `genRange` being deprecated.

> Now I know that the bad algorithm of v1.1 random happened to (mis)use next. (This wasn't mentioned in the blog post.)

The blog post only showed the performance issues, which later led to fixes in version `random-1.2`.

> So, I think next itself is innocent. The fault was with random for misusing next.

Couldn't be further from the truth. `next`+`genRange` are at fault because with such general interface efficient random number generation is impossible. The fact that splitmix or any other PRNG for that matter have efficient implementation for `next` is totally irrelevant. So, `next` was more than just redundant, it was an obstacle and that is why it is now deprecated.

**Comment by 2jacobtan** [comment]
Okay, I now understand that `next` was never really suited for the purpose it was supposed to serve.

And the end user should use `uniform` (supersedes `random`).

Thanks Alexey!

**Comment by anka-213** [comment]
Should we add something like this as a clarification to the deprecation notice?

> End users should use `random` or `uniform` instead

**Comment by anka-213** [comment]
It might also be worth moving the `RandomGen` class further down in the haddock, since having it at the top makes it feel like it is the main interface to the module, while in actuality it's mostly an implementation detail that is only relevant for those who want to define their own PRNG.

**Comment by lehins** [comment]
> It might also be worth moving the RandomGen class further down in the haddock, since having it at the top makes it feel like it is the main interface to the module

It is the main interface, because without understanding the class you cannot use the rest of the module. So, it is in fact the key concept in the whole package, therefore I do believe `RandomGen` is at its rightful place at the top of the module.

> Should we add something like this as a clarification to the deprecation notice?

Saying use `random` instead of `next` is wrong, because they were never the same concept. This whole ticket makes me realize that `next` needed deprecation long time ago regardless of its performance implications, because I suspect people were wrongfully using it to generate random `Int` values.

It is ok to use all functions in the library, including the ones in `RandomGen`. It is only deprecated functions that should not be used. "Deprecated: No longer used" - clearly means do not use it. I don't understand why any extra clarification is necessary.

There is plenty of explanation with many examples in the documentation of all concepts in the library. Users just needed to do due diligence and read it carefully.

At the very top of the module is the great summary of the main concepts in the module. One of the first things in the module is the usage paragraph, which clearly states what needs to be done in order to generate random values. If that is the only thing you read in the whole of haddock, it is already enough to be able to properly use the library.

![image](https://user-images.githubusercontent.com/2333894/125601918-c77e7a2f-6997-4cb7-9003-0c0e601b7ba4.png)

@anka-213 With all that said, if you think that documentation can use some improvements, please feel free to submit a PR and we will discuss it.

**Comment by fintara** [comment]
Sorry, but if `uniform` is to replace `next`, what should I use instead of `genRange`? I have read a few issues, and all of them say that it's deprecated.

The changelog says

> Version 1.2.0 introduces genWord64, genWord32 and similar methods to the RandomGen class. The significantly slower method next and its companion genRange are now deprecated.

which suggests that `genWord64` etc. are the successors, but it doesn't look like it. 

So, what should I use instead of `genRange`?
