### ISSUE TITLE
How do I put this into my stack project?

### ISSUE THREAD

**Issue by eboatwright** [haskell/random#129]
First, I tried adding it to the .cabal file. Whenever I ran stack run, it would remove it. So, then I tried adding it to stack.yaml. After some trying, and clearing cache, I got stack build working without an error. But, if I try to import it into my Main.hs file, with `import System.Random` It returns an error saying that it can't find that module

**Comment by lehins** [comment]
This question is unrelated to `random`. Moreover, github issue tracker is for reporting bugs and requesting features. I can recommend trying [stackoverflow.com](https://stackoverflow.com/questions/tagged/haskell-stack) for this sort of questions

**Comment by eboatwright** [comment]
Well, I already checked all the stackoverflow "answers" and none of them worked

**Comment by lehins** [comment]
@eboatwright, have you tried "asking" a question on stackoverflow.com? That is what the whole platform was designed for: if the question you are looking an answer for have never been asked before you can submit your own question.

All I am saying is that Github is not a place to ask general questions on how a library is suppose to be used, especially since your question is completely unrelated to `random` library, your issue is with the way you are using your dev tools.

**Comment by eboatwright** [comment]
ok
