### ISSUE TITLE
randmomR produces only even values

### ISSUE THREAD

**Issue by drautzburg** [haskell/random#30]
There is thread on haskell-beginners about [this issue](https://mail.haskell.org/pipermail/beginners/2015-October/015996.html). In short I found that

`length $ filter even $ map (\s -> fst $ randomR (1::Int,10) (mkStdGen s))[1..1000]`

returns 1000, i.e. all values were even numbers, no matter what seed I provided.

**Comment by cartazio** [comment]
Random is known to be poor quality. There will be a new release that passes
big crush coming this fall.

Of packages currently on hackage, only pcg random passes big crush.

Stay tuned. But if you need good quality prng tomorrow, pcg random is
available.  Though programs will incur a prim monad constraint.

**Comment by idontgetoutmuch** [comment]
This is a long-standing issue see https://github.com/haskell/random/issues/25. Personally I would be inclined to use https://hackage.haskell.org/package/tf-random as this is what QuickCheck uses https://hackage.haskell.org/package/QuickCheck-2.8.1. I believe @cartazio has run some tests on this and on splitmix. I hoping he will post these soon so we can put forward a proposal to fixing this.

Of course there is always Dilbert's view:  http://dilbert.com/strip/2001-10-25.

**Comment by cartazio** [comment]
this is going to be addressed by the work in  #31

**Comment by kuk0** [comment]
i wouldn't call it "poor quality" - this is totally unusable
```
Prelude> import System.Random
Prelude System.Random> let dieRoll = fst . randomR (1,6) . mkStdGen :: Int -> Int
Prelude System.Random> map dieRoll [1..20]
[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6]
```
this is Dilbert...

**Comment by cartazio** [comment]
Agreed :)
If you want to brain storm on ticket or via email or IRC , more ideas the
better.

I've been meaning to give random some proper tlc, and the more ideas the
better :)

**Comment by idontgetoutmuch** [comment]
It's not ideas that are in short supply. We know we need to a) test the various PRNGs against the various randomness tests (and in particular L'Ecuyers Test01 suite) and b) test their performance.

I have a colleague who is an expert in the field of RNGs but who does not know Haskell. I have created a binding from R to allow him to test their effectiveness https://github.com/idontgetoutmuch/RandomHaskellFromR. I don't think we need a Haskell binding to Test01 (since we can call it from R) but we have one anyway: https://github.com/idontgetoutmuch/RandomHaskellFromR.

One useful thing someone could do would be to create a runnable and repeatable performance test suite maybe using https://github.com/nkartashov/prng-bench but note the issue I raised with it.

My suspicion is that SplitMix will probably be a good replacement but we don't know yet. QuickCheck uses https://hackage.haskell.org/package/tf-random but my testing of it with Test01 didn't inspire me with confidence.

If I sound frustrated, it's because I am.

**Comment by idontgetoutmuch** [comment]
It seems my test of tf-random shows it passes at least small crush so ignore my lack of inspiration in the comment above.

> I have made some small progress e.g. I can now show that tf-random passes smallcrush:

> [OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK,OK]
> But I am having problems using htestu at the command line - see: nkartashov/htestu#3.
