### ISSUE TITLE
Generalize randomIO, randomRIO

### ISSUE THREAD

**Issue by kuk0** [haskell/random#34]
The `System.Random` module is a mix of general purpose abstracted functions like random, randomR taking any PRNG, plus an implementation of one specific bad PRNG.

Can we separate these into one abstract module/package which doesn't depend on a particular PRNG implementation and multiple modules implementing PRNGs?

Specifically, the `Random` class contains functions `randomRIO` and `randomIO`, which _only_ work for the crappy standard PRNG (and it seems to me they are not reusable with System.Random.TF - which lacks this functionality)

**Comment by cartazio** [comment]
Hello!
Let's brain storm this out.
I'll be starting work on the v2.0 random branch properly this weekend.
More ideas the better

**Comment by kuk0** [comment]
cool, great to hear that!

**Comment by cartazio** [comment]
If you want to talk, the #numerical-Haskell IRC channel on freenode is a
good way to reach me, and I do have a tendency to focus more on topics
people talk with me about :)

**Comment by kuk0** [comment]
what nick?

**Comment by cartazio** [comment]
The one with my name. :)

**Comment by cartazio** [comment]
Carter, just to be clear.   :)
Also happy to video chat some time

**Comment by cartazio** [comment]
But yes, v2 should absolutely have such improvements.

One question I've been trying to research is is there a good system
randomness source on Windows? My understanding is that on Linux,
/Dev/urandom or the new random sys call is recommended, and Dev/random on
Mac / bsd variants is recommended there. I suppose I should look at the
entropy lib I think some other folks have been using to see if there's
already code for that third case lying around :)

**Comment by lehins** [comment]
@kuk0 I am happy to let you know that such interface has now been implemented. See #62 and the new random-1.2.0 release. 

Using `uniformM`, `uniformRM` together with `IOGen` or `AtomicGen` you can get the desired interface with any pure RNG, such as no longer crappy `StdGen` and `TFGen`.

It is still possible to use `randomIO` and `randomRIO`, but those are left for backward compatibility and I'd discourage their usage at all, since using a global mutable variable goes against Haskell best practices.
