### ISSUE TITLE
Function to get a random element from a list

### ISSUE THREAD

**Issue by MaxGabriel** [haskell/random#80]
In Haskell, getting a random element from a list might look like this:

```haskell
i <- randomRIO (0, length l - 1)
return $ l !! i
```

In languages like Ruby, there's a handy helper function for this, [sample](https://ruby-doc.org/core-1.9.3/Array.html#method-i-sample). Would the random package be open to such a function?

I imagine there are many fiddly details to this—does it return a Maybe for lists, and is there also a version for NonEmptyLists? Is there a version that can return multiple elements? How does that function handle invalid size parameters? Are there versions that work in IO and versions that work with a RandomGen? etc. But, to start wanted to just check if just generally this function would be accepted.

**Comment by lehins** [comment]
I don't think this is the right abstraction for the pure lazy language like Haskell. Here are some more issues with it, besides the ones you've already mentioned:

* grabbing a random element from a list can return bottom (diverge) because a list can be infinite
* problems with efficiency: getting the length and then indexing into a list are both O(n) operations. (this can be worked around with different implementation)
* should it return repeat elements, in case when random index is the same? Ruby's `sample` does NOT return duplicates, but that means it keeps some sort mutable state around to track which items has already been returned. That's not the right approach for Haskell.

A more appropriate would be something like `shuffle`, that randomizes the list and then you can take a ranodm element one by one from the head of the list. But even shuffle has many nuances. Moreover, I am not sure if `random` package is the right place for such function, especially considering that there are others that provide this functionality. For example both [`randomElement`](https://hackage.haskell.org/package/random-fu-0.2.7.7/docs/Data-Random-List.html#v:randomElement) and [`shuffle`](https://hackage.haskell.org/package/random-fu-0.2.7.7/docs/Data-Random-List.html#v:shuffle) in a more complete toolbox-like `random-fu` package that utilizes `random` underneath.

I'll live the ticket opened for now, see if anyone else has some comments on this topic.

**Comment by Bodigrim** [comment]
@lehins I was also thinking about `shuffle` being a better abstraction. But I agree that even it feels too opinionated for `random`. There are several packages dedicated to shuffling already on Hackage:
http://hackage.haskell.org/package/random-shuffle-0.0.4/docs/System-Random-Shuffle.html
http://hackage.haskell.org/package/pure-shuffle-0.1.1.1/docs/Algorithms-Random-Shuffle-Pure.html

**Comment by MaxGabriel** [comment]
You raise some good points, but don't:

* grabbing a random element from a list can return bottom (diverge) because a list can be infinite
* problems with efficiency: getting the length and then indexing into a list are both O(n) operations. (this can be worked around with different implementation)

apply to many functions in `base`, including very basic functions like `last`?

**Comment by MaxGabriel** [comment]
`shuffle` is inherently going to be much slower than picking a random element, correct? It doesn't seem good to push shuffling a whole list to get a single element

**Comment by lehins** [comment]
I wouldn't go as far as "many" functions, but yes, some of them can't deal with infinite lists, good examples are `reverse` or `foldl`. At the same time I'd recommend staying away from functions like `last` and `!!` precisely because they are inefficient and dangerous.

> shuffle is inherently going to be much slower than picking a random element, correct? It doesn't seem good to push shuffling a whole list to get a single element

Haskell is a lazy language, so shuffling a list and grabbing the head could potentially be as fast as getting a single random element. Just in case here is another `shuffle` from [`mwc-random`](https://www.stackage.org/haddock/nightly-2020-08-26/mwc-random-0.14.0.0/System-Random-MWC-Distributions.html#v:uniformShuffle) behaves in a way you were thinking of. That one will be inherently slower than just drawing a random element from a vector because it does allocation of a full new copy with all its elements shuffled.

The major problem with your suggestion is not that `sample` is not a useful functionality to have, but the fact that implementing this functionality on lists as efficiently as it can be done for example for a mutable array is not possible and I do not want to add slow functions to core package like `random`, because people WILL use them. Note that the `sample` function you linked to works on arrays, not on lists, and for a good reason.

In any case, I agree with @Bodigrim such function is too opinionated for `random`. I will however keep an eye on a good place for this functionality and will ping you @MaxGabriel if I do find it.

**Comment by Shimuuar** [comment]
> Haskell is a lazy language, so shuffling a list and grabbing the head could potentially be as fast as getting a single random element. 

Only if you're willing to consume PRNG and to create  stream of random numbers. Otherwise one have to complete shuffle in order to get new PRNG state

**Comment by Bodigrim** [comment]
> Only if you're willing to consume PRNG and to create stream of random numbers.

My understanding is that you can split PRNG into two, return the first one back and consume the second one to create a stream of random numbers.
